@startuml

skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS gérer les questionnaires
actor ":Enseignant" as c
participant ":Système" as s
c->s : manageQuestions()
c<<--s : affiche toute les questions du cours
c->s : Sélectionne l'option pour ajouter une question 
c->s : addQuestion(.....)
c<<--s : affiche la question
c<<--s : affiche toutes les questions reliés au cours
c<<--s : affiche un message de confirmation d'ajout de la question

@enduml