@startuml
title SGA — MDD 

class Universite {
  listeEtudiants: Map<String, Etudiant>
  listeEnseignants: Map<String, Enseignant>
}

class Cours {
  id: string 
  titre: string
}

class CoursGroupe {
  id: string        
  groupeId: string
  titre: string
  enseignant: Enseignant
  listeEtudiants: Map<String, Etudiant>
}

class Enseignant {
  email: string
  prenom: string 
  nom: string
  token: string
  listeCours: Map<String, CoursGroupe>
}

class Etudiant {
  id: string
  prenom: string
  nom: string
}

enum Mode { 
  PRESENCE 
  DISTANCE 
  HYBRIDE 
}

' Une séance d’horaire (cours, labo, TP…)
class Horaire {
  jour: string     
  heure: string
  activite: string
  mode: Mode
  local: string
}

Universite "1" -- "0..*" Etudiant : contient >
Universite "1" -- "0..*" Enseignant : contient >

Cours "1" -- "0..*" CoursGroupe : identifie >
CoursGroupe "1" -- "0..*" Horaire : est offert selon >
Etudiant "0..*" -- "0..*" CoursGroupe : s'inscrit à >
Enseignant "1" -- "0..*" CoursGroupe : responsable >
@enduml

@enduml
