@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour afficher une liste de groupe-cours
participant ":ControleurCours" as c
->c : getListeCours(courriel)
note right : selon Contrôleur
participant ":SGB" as j
c->j : getListeCours(courriel)
note right : selon Expert
c<--j : L = getListeCours(courriel)
<--c : return L

@enduml